#!/bin/bash

#for package in $(apt list --installed) ; do
#    echo "Package: $package"
#    sleep 2
#done       


#var1=10

#while [ $var1 -gt 0 ]; do
#	echo $var1
#	var1=$[$var1 - 1]
#	sleep 1
#done

#IFS=$'\n'
#
#for entry in $(cat /etc/passwd); do
#	echo "Values in $entry --"
#	IFS=:
#
#	for value in $entry; do
#		echo $value
#	done
#done

IFS=:

for folder in $PATH; do
	echo "$folder: -----------------------------------------------"

	for file in $folder/*; do
		if [ -x $file ]; then
			echo " $file"
		fi
	done
done
