#!/bin/bash

for i in B D M J P R S T L N ; do
    for j in A E I O U Y R T L H ; do
        for k in A C D E O R S T L N ; do
            for l in E D H K Y R S T L N ; do
	        echo $i $j $k $l
	    done
	done
    done	
done

